
filegroup(
  name = "libcartographer_module.so_release", 
  srcs = ["libcartographer_module.so"],
  visibility = ["//visibility:public"],
)
 
filegroup(
  name = "libnavigation_module.so_release", 
  srcs = ["libnavigation_module.so"],
  visibility = ["//visibility:public"],
)
 